baseURL = 'https://www.aionsec.ai/'
languageCode = 'en-us'
title = 'AIONSEC'
theme = 'gokarna'

[params]
  description = "| Never Stop Hunting |"
  footer = "AIONSEC"


  avatarURL = "/images/aionsec.png"
  avatarAltText = "aionsec"
  avatarSize = "size-l"

  # link hover colors (Dracula Pink)
  accentColor = "#eb89f4"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
  name = "about"
  url = "/about/"
  weight = 1