baseURL = 'https://www.aionsec.ai/'
languageCode = 'en-us'
title = 'aionsec'
theme = 'gokarna'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[menu]


[[menu.main]]
name = "about"
url = "/about/"
weight = 1



